{% set version = "4.5.3" %}

package:
  name: pelican
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pelican/pelican-{{ version }}.tar.gz
  sha256: 7a769a233561c104341d53500046079d10f72bc19e5d6d99521cce5328219bd9

build:
  number: 0
  noarch: python
  script:
    - rm -f pyproject.toml
    - {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pelican = pelican:main
    - pelican-import = pelican.tools.pelican_import:main
    - pelican-quickstart = pelican.tools.pelican_quickstart:main
    - pelican-themes = pelican.tools.pelican_themes:main

requirements:
  host:
    - python >=3.6,<4.0
    - pip
  run:
    - python >=3.6,<4.0
    - blinker >=1.4,<2.0
    - docutils >=0.16,<0.17
    - feedgenerator >=1.9,<2.0
    - jinja2 >=2.11,<2.12
    - pygments >=2.6.1,<2.7.0
    - python-dateutil >=2.8,<3.0
    - pytz >=2020.1,<2021.0
    - unidecode >=1.1,<2.0

test:
  imports:
    - pelican
    - pelican.tools
  commands:
    - pelican --help
    - pelican-import --help
    - pelican-themes --help

about:
  home: http://getpelican.com/
  license_file: LICENSE
  license: AGPL-3.0-only
  summary: A tool to generate a static blog from reStructuredText or Markdown input files.

extra:
  recipe-maintainers:
    - ocefpaf
    - mwcraig
