{% set version = "4.2.0" %}

package:
  name: pelican
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pelican/pelican-{{ version }}.tar.gz
  sha256: be7ea9a09311374322b5579c88975ae003409e40c833e761780a0d0dbd84e756

build:
  number: 0
  noarch: python
  script:
    - rm -f pyproject.toml
    - "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - pelican = pelican:main
    - pelican-import = pelican.tools.pelican_import:main
    - pelican-quickstart = pelican.tools.pelican_quickstart:main
    - pelican-themes = pelican.tools.pelican_themes:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - feedgenerator >=1.9
    - jinja2 >=2.7
    - pygments
    - docutils
    - pytz >=0a
    - blinker
    - unidecode
    - six >=1.4
    - python-dateutil

test:
  imports:
    - pelican
    - pelican.tools
  commands:
    - pelican --help
    - pelican-import --help
    - pelican-themes --help

about:
  home: http://getpelican.com/
  license_file: LICENSE
  license: AGPL-3.0
  summary: 'A tool to generate a static blog from reStructuredText or Markdown input files.'

extra:
  recipe-maintainers:
    - ocefpaf
    - mwcraig
