{% set name = "pelican" %}
{% set version = "4.0.0" %}
{% set sha256 = "ad22bf8f141ce0989855106c49a7ab55ca2bcc9541e71cc8fb8cf55f394407fe" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - pelican = pelican:main
    - pelican-import = pelican.tools.pelican_import:main
    - pelican-quickstart = pelican.tools.pelican_quickstart:main
    - pelican-themes = pelican.tools.pelican_themes:main

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - feedgenerator
    - jinja2
    - pygments
    - docutils
    - pytz
    - blinker
    - unidecode
    - six
    - python-dateutil
    - ghp-import

test:
  imports:
    - pelican
    - pelican.tools
  commands:
    - pelican --help
    - pelican-import --help
    - pelican-themes --help
    #- pelican-quickstart --help

about:
  home: http://getpelican.com/
  license_file: LICENSE
  license: AGPL-3.0
  summary: 'A tool to generate a static blog from reStructuredText or Markdown input files.'

extra:
  recipe-maintainers:
    - ocefpaf
    - mwcraig
