{% set name = "pelican" %}
{% set version = "4.5.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pelican-{{ version }}.tar.gz
  sha256: 0e9de7f4c7a2a21784f8aed9c7df6003cebfb39a36d0adbafd303d66649dc3ad

build:
  number: 0
  noarch: python
  entry_points:
    - pelican = pelican.__main__:main
    - pelican-import = pelican.tools.pelican_import:main
    - pelican-plugins = pelican.plugins._utils:list_plugins
    - pelican-quickstart = pelican.tools.pelican_quickstart:main
    - pelican-themes = pelican.tools.pelican_themes:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
  run:
    - python >=3.6,<4.0
    - blinker >=1.4,<2.0
    - docutils >=0.16,<0.17
    - feedgenerator >=1.9,<2.0
    - jinja2 >=2.11,<2.12
    - pygments >=2.6.1,<2.7.0
    - python-dateutil >=2.8,<3.0
    - pytz >=2020.1,<2021.0
    - unidecode >=1.1,<2.0

test:
  imports:
    - pelican
    - pelican.plugins
  commands:
    - pip check
    - pelican --help
    - pelican-import --help
    - pelican-plugins --help
    - pelican-quickstart --help
    - pelican-themes --help
  requires:
    - pip

about:
  home: http://getpelican.com/
  license_file: LICENSE
  license: AGPL-3.0-only
  summary: A tool to generate a static blog from reStructuredText or Markdown input files.

extra:
  recipe-maintainers:
    - ocefpaf
    - mwcraig
