travis:
  secure:
    BINSTAR_TOKEN: OA8BSrOKW13a0D5qojC/gsWVg72PROjXEmnyOqT7w69u/xSHkYu7vSioRnyJr22DPRsPsoF9GICeaozzAsaa/IIMFwR6KQxdvIjWkLRXupBpxnfwtyhe2OqwiftBgTcvvfDovde5Wqz8dP0ph4Nv6Dy5cEpKPwTLpQSUd0Q7eTRk+q9HyuoLX7mOaORZkUnZM7wFwr8bDSEenEVHadeSJ7ILyLnixSTpxjOl0/jzEvl0epEVlkBLcsuVfGSqX1nQPNAeYYZoxLi2Uwb8uNwa5fMDTgpOkttXphU5j6n5noYSDZvFw5yAaDgdZ7R1rxkgUGLFG8bu9qXM2RVzXj2KPL2/Q/afrhI5oWy1xfDoTOBglfToz/rfvrne/ItxYT6I5UBvp7ULpR02ZVrOOMuULKrr0r3rFulOl2iFuLvtOaUawTBs5TBw+t+CSRjd13qMFFlPjmvowhjULl99Ix2B17vcbJbyqp9PJ/ebXRkB3Ik2MNRqDUi4cUpaT9lJWD2gqmCE2Zu4821j6JUyuLkINrbYhGW+TLsvNBB5avTH4HSoH2eMcCovBb/GXwYblAVoe/0LJLAVCjTrYfevnTU54Jse/k9cAFrdlSFQBole9qUcOk2ezJKqr/ThKAV21szxeSlppv/jGRrFjQ8FmXLS7MtCKk+Mo5sTTkw3a0gmaD4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
