travis:
  secure:
    BINSTAR_TOKEN: M/flDM8jMzOzIz/diATJNjld18UvPWkDfQ/b+1H95Krw+Ifg3/Rm9mX3HvFor72YhfVdrN+ZT8JUSD0UN0Cu0K/Z2RT4WNDz7slB1bVr4hteNZKQtgvbtroHXNYcSfYmLnoh7I+Fn4vMa/+ZAuVnTT6Z8wz0V+S6LfzUYGBt7d7otOL1yeJ2TDjW14tKKJV4bx+F9UGVxjyOPn8DGTKMuvhyq6CCOUcLJWzFnxZ8KIOv13cRbbD5fJ2uGeFmZnyAxAChUr/668oBzU71wMvEni7xtLjIqMXC/JaPRpXEtRABtnm1LazMJaAmNzF0J5y+Y5HBTw9jz/KMz8TEpMa0mgndVjYF5ZmSYjk6pnY258aKJW2+mP+m6XiXkKnr/LpgXMV3TMuebHDBDaDsZ8sn31A2uly1zJIoh+mkjRpc+9dL3T9U9J5SUOTI6GEB4Hd/KWmRy/xX1skv2PyjsHuUJ5lv/eyI/u5ptt3QFok/nbQUbyhVgATFycSEUIBn8pvn7KaGZd8g5xMsmQ+w+w4BaIXOnrosIWUINi0qYERtyhsHPddEnu6RVevDJwjbeibLVsLrtgvSHxADEIzEOK/icjhYWJrkyT0hwYTmpmTfqQdc/QQXXSKcXAd1K3zfip3NJW1DLM7p7H3HAvWTGzkWx7GkzFNzhk61H2ptQoKen2U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
